// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: linkedRoles.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace tobeh.TypoLinkedRolesService {

  /// <summary>Holder for reflection information generated from linkedRoles.proto</summary>
  public static partial class LinkedRolesReflection {

    #region Descriptor
    /// <summary>File descriptor for linkedRoles.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LinkedRolesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFsaW5rZWRSb2xlcy5wcm90bxILbGlua2VkUm9sZXMaG2dvb2dsZS9wcm90",
            "b2J1Zi9lbXB0eS5wcm90bzINCgtMaW5rZWRSb2xlc0IfqgIcdG9iZWguVHlw",
            "b0xpbmtlZFJvbGVzU2VydmljZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
