// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: linkedRoles.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace tobeh.TypoLinkedRolesService {
  public static partial class LinkedRoles
  {
    static readonly string __ServiceName = "linkedRoles.LinkedRoles";


    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::tobeh.TypoLinkedRolesService.LinkedRolesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for LinkedRoles</summary>
    public partial class LinkedRolesClient : grpc::ClientBase<LinkedRolesClient>
    {
      /// <summary>Creates a new client for LinkedRoles</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LinkedRolesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LinkedRoles that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LinkedRolesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LinkedRolesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LinkedRolesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LinkedRolesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LinkedRolesClient(configuration);
      }
    }

  }
}
#endregion
