services:
  typo-linked-roles-service:
    container_name: typo-linked-roles-service
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    ports:
      - "5221:8080"
    volumes:
      - path-to-appsettings.json:/app/appsettings.json